// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OrderProcessing.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class InventoryReserved : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""InventoryReserved"",""namespace"":""OrderProcessing.Events"",""fields"":[{""name"":""OrderId"",""type"":""string""},{""name"":""ReservationId"",""type"":""string""},{""name"":""ReservedItems"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""ReservedItem"",""namespace"":""OrderProcessing.Events"",""fields"":[{""name"":""ProductId"",""type"":""string""},{""name"":""Quantity"",""type"":""int""},{""name"":""WarehouseId"",""type"":""string""}]}}},{""name"":""ReservationDate"",""type"":""long""},{""name"":""ExpirationDate"",""type"":""long""}]}");
		private string _OrderId;
		private string _ReservationId;
		private IList<OrderProcessing.Events.ReservedItem> _ReservedItems;
		private long _ReservationDate;
		private long _ExpirationDate;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return InventoryReserved._SCHEMA;
			}
		}
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		public string ReservationId
		{
			get
			{
				return this._ReservationId;
			}
			set
			{
				this._ReservationId = value;
			}
		}
		public IList<OrderProcessing.Events.ReservedItem> ReservedItems
		{
			get
			{
				return this._ReservedItems;
			}
			set
			{
				this._ReservedItems = value;
			}
		}
		public long ReservationDate
		{
			get
			{
				return this._ReservationDate;
			}
			set
			{
				this._ReservationDate = value;
			}
		}
		public long ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				this._ExpirationDate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.ReservationId;
			case 2: return this.ReservedItems;
			case 3: return this.ReservationDate;
			case 4: return this.ExpirationDate;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.String)fieldValue; break;
			case 1: this.ReservationId = (System.String)fieldValue; break;
			case 2: this.ReservedItems = (IList<OrderProcessing.Events.ReservedItem>)fieldValue; break;
			case 3: this.ReservationDate = (System.Int64)fieldValue; break;
			case 4: this.ExpirationDate = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
