// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OrderProcessing.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class OrderCreated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderCreated"",""namespace"":""OrderProcessing.Events"",""fields"":[{""name"":""OrderId"",""type"":""string""},{""name"":""CustomerId"",""type"":""string""},{""name"":""OrderDate"",""type"":""long""},{""name"":""Items"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""OrderItem"",""namespace"":""OrderProcessing.Events"",""fields"":[{""name"":""ProductId"",""type"":""string""},{""name"":""Quantity"",""type"":""int""},{""name"":""UnitPrice"",""type"":""double""}]}}},{""name"":""TotalAmount"",""type"":""double""}]}");
		private string _OrderId;
		private string _CustomerId;
		private long _OrderDate;
		private IList<OrderProcessing.Events.OrderItem> _Items;
		private double _TotalAmount;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderCreated._SCHEMA;
			}
		}
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		public string CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				this._CustomerId = value;
			}
		}
		public long OrderDate
		{
			get
			{
				return this._OrderDate;
			}
			set
			{
				this._OrderDate = value;
			}
		}
		public IList<OrderProcessing.Events.OrderItem> Items
		{
			get
			{
				return this._Items;
			}
			set
			{
				this._Items = value;
			}
		}
		public double TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				this._TotalAmount = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.CustomerId;
			case 2: return this.OrderDate;
			case 3: return this.Items;
			case 4: return this.TotalAmount;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.String)fieldValue; break;
			case 1: this.CustomerId = (System.String)fieldValue; break;
			case 2: this.OrderDate = (System.Int64)fieldValue; break;
			case 3: this.Items = (IList<OrderProcessing.Events.OrderItem>)fieldValue; break;
			case 4: this.TotalAmount = (System.Double)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
