// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OrderProcessing.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class OutOfStock : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OutOfStock"",""namespace"":""OrderProcessing.Events"",""fields"":[{""name"":""OrderId"",""type"":""string""},{""name"":""UnavailableItems"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""UnavailableItem"",""namespace"":""OrderProcessing.Events"",""fields"":[{""name"":""ProductId"",""type"":""string""},{""name"":""RequestedQuantity"",""type"":""int""},{""name"":""AvailableQuantity"",""type"":""int""}]}}},{""name"":""RejectionDate"",""type"":""long""}]}");
		private string _OrderId;
		private IList<OrderProcessing.Events.UnavailableItem> _UnavailableItems;
		private long _RejectionDate;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OutOfStock._SCHEMA;
			}
		}
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		public IList<OrderProcessing.Events.UnavailableItem> UnavailableItems
		{
			get
			{
				return this._UnavailableItems;
			}
			set
			{
				this._UnavailableItems = value;
			}
		}
		public long RejectionDate
		{
			get
			{
				return this._RejectionDate;
			}
			set
			{
				this._RejectionDate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.UnavailableItems;
			case 2: return this.RejectionDate;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.String)fieldValue; break;
			case 1: this.UnavailableItems = (IList<OrderProcessing.Events.UnavailableItem>)fieldValue; break;
			case 2: this.RejectionDate = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
