// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OrderProcessing.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class PaymentProcessed : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PaymentProcessed"",""namespace"":""OrderProcessing.Events"",""fields"":[{""name"":""OrderId"",""type"":""string""},{""name"":""PaymentId"",""type"":""string""},{""name"":""Amount"",""type"":""double""},{""name"":""Status"",""type"":{""type"":""enum"",""name"":""PaymentStatus"",""namespace"":""OrderProcessing.Events"",""symbols"":[""SUCCESSFUL"",""FAILED"",""PENDING""]}},{""name"":""TransactionDate"",""type"":""long""},{""name"":""PaymentMethod"",""type"":""string""}]}");
		private string _OrderId;
		private string _PaymentId;
		private double _Amount;
		private OrderProcessing.Events.PaymentStatus _Status;
		private long _TransactionDate;
		private string _PaymentMethod;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PaymentProcessed._SCHEMA;
			}
		}
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		public string PaymentId
		{
			get
			{
				return this._PaymentId;
			}
			set
			{
				this._PaymentId = value;
			}
		}
		public double Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		public OrderProcessing.Events.PaymentStatus Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				this._Status = value;
			}
		}
		public long TransactionDate
		{
			get
			{
				return this._TransactionDate;
			}
			set
			{
				this._TransactionDate = value;
			}
		}
		public string PaymentMethod
		{
			get
			{
				return this._PaymentMethod;
			}
			set
			{
				this._PaymentMethod = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.PaymentId;
			case 2: return this.Amount;
			case 3: return this.Status;
			case 4: return this.TransactionDate;
			case 5: return this.PaymentMethod;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.String)fieldValue; break;
			case 1: this.PaymentId = (System.String)fieldValue; break;
			case 2: this.Amount = (System.Double)fieldValue; break;
			case 3: this.Status = (OrderProcessing.Events.PaymentStatus)fieldValue; break;
			case 4: this.TransactionDate = (System.Int64)fieldValue; break;
			case 5: this.PaymentMethod = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
