// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OrderProcessing.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class ReservedItem : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ReservedItem\",\"namespace\":\"OrderProcessing.Events\",\"fiel" +
				"ds\":[{\"name\":\"ProductId\",\"type\":\"string\"},{\"name\":\"Quantity\",\"type\":\"int\"},{\"nam" +
				"e\":\"WarehouseId\",\"type\":\"string\"}]}");
		private string _ProductId;
		private int _Quantity;
		private string _WarehouseId;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ReservedItem._SCHEMA;
			}
		}
		public string ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				this._ProductId = value;
			}
		}
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				this._Quantity = value;
			}
		}
		public string WarehouseId
		{
			get
			{
				return this._WarehouseId;
			}
			set
			{
				this._WarehouseId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ProductId;
			case 1: return this.Quantity;
			case 2: return this.WarehouseId;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ProductId = (System.String)fieldValue; break;
			case 1: this.Quantity = (System.Int32)fieldValue; break;
			case 2: this.WarehouseId = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
